---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: "whdc"
  name: "whdc-nfs-app"
  labels:
    type: local
spec:
  storageClassName: "manual"
  claimRef:
    name: "whdc-pvc-app"
    namespace: "whdc"
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/whdc/app
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "whdc"
  name: "whdc-pvc-app"
spec:
  storageClassName: "manual"
  volumeName: "whdc-nfs-app"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
status: {}
