---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "whdc"
  name: "whdc-db-claim"
spec:
  storageClassName: "manual"
  volumeName: "whdc-db-volume"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
